### ISSUE TITLE
Czech clone

### ISSUE THREAD

**Issue by xsuchy** [badlogic/heissepreise#145]
This is great. I want to run a clone for the Czech Republic with data from shops in Czechia.

I would like to do a few things here as well:

[ ] in README point to fork https://github.com/xsuchy/heissepreise-cz
[ ] in https://heisse-preise.io have link to http://slevnena-cena.cz/

Anyone willing to collaborate on Czech fork is welcome. 

If there will be any commit that is general, I will forward it here to the original repo.

**Comment by Darkyenus** [comment]
Do we want regional variants as independent forks, or would you, @badlogic, be willing to host it from one central location, with localization and, possibly, multiple URLs?

The benefit of doing it all centrally would be that the upgrades would be automatically applied for everyone and it would be trivial to compare prices across the border (which might be practically useful, many Czechs travel to neighboring countries for shopping and doubt we are the only ones).

The downsides of central hosting are clear as well, I think.

----
I am currently working on dynamic localization (I'm trying to understand how it all works and what would be the best way to implement it, right now).

**Comment by badlogic** [comment]
Since the site is hostes under my name, it'd mean I'd expose myself to any
legal issues in countries outside Austria. I'd rather not do that.

What we should do is make it configurable which stores are fetched by
default, so forks just have to modify say a .json file the client fetches
first, which tells it which data files to fetch. This would make it easy to
keep controbutions in this repo, while forks deploy with a custom data file
.json

**Comment by bergonzzi** [comment]
I would also be interested in cloning this for Portugal. Will keep an eye on updates.

**Comment by badlogic** [comment]
There aren't likely any updates regarding this from our side, save for possibly the config file I mentioned the client uses to decide for which stores to pull data from.

Please simply fork the repository and send a PR with a modification of the README.md that links to your fork and possibly live site.
