### ISSUE TITLE
Interest in Hofer support?

### ISSUE THREAD

**Issue by mhochsteger** [badlogic/heissepreise#3]
What are the reasons for Hofer missing in the shops (legal, technical)?

I started to work on it and managed to fetch about 800 articles (need to get pagination working, also you need an access token, so it's more involved).

Is there any interest on adding Hofer support?

**Comment by mhochsteger** [comment]
@badlogic opened PR (pagination and fetching access token is working now).

**Comment by GGegenhuber** [comment]
@mhochsteger while you implemented Hofer support via roksh.at I was checking out the corresponding Android app.

Not sure whether there is any difference between the listed products on roksh.at and the products that are shown via the app. Anyway, for reference (and since it's always good to have a fallback solution), this is the endpoint that is used within the app:

`curl "https://mabe.int.prod.ci-aldi.com/mabe/api/v1/product/search?sort=recommended&currentPage=0&query=brot%3A%3AcontentType%3APRODUCT&pageSize=100" -H "x-api-key: 7WoOhef9TSSTu037iyaI-4ZlPQQctC8e9fj9Z5anH7M" -H "locale: at-DE"`

The maximum response size is 100 products; the "pagination" key in the JSON response contains additional information regarding the number of total products that are available.

Conveniently, this endpoint is also used by Hofer apps of other countries (e.g., DE, IT, HU).
In my opinion, adding a German retailer as a reference could be interesting (similar market conditions, but probably more competition between the existing supermarket chains).
To get the results of the German app (i.e., Aldi Sued), simply change the locale header to `de-DE`:
`curl "https://mabe.int.prod.ci-aldi.com/mabe/api/v1/product/search?sort=recommended&currentPage=0&query=brot%3A%3AcontentType%3APRODUCT&pageSize=100" -H "x-api-key: 7WoOhef9TSSTu037iyaI-4ZlPQQctC8e9fj9Z5anH7M" -H "locale: de-DE"`

**Comment by badlogic** [comment]
Wonder if wildcard queries and massive page sizes work with that endpoint :)

**Comment by badlogic** [comment]
Merge the corresponding PR and fixed it up. The `replay()` function in `analysis.js` won't play nice if we don't have historical data for every day for each store. Currently doesn't take Hofer into account. I'll fix that up eventually.

**Comment by GGegenhuber** [comment]
> Wonder if wildcard queries and massive page sizes work with that endpoint :)

As far as I could test the pageSize param for this endpoint is limited to 100 products.

For now, I did not find an easy way to enumerate all existing products.
Hofer divides its product into various product categories that can be queried via another endpoint, e.g.,
HOFER Preis - Dauerhaft Günstiger (143 products): StructureGroup_1588161341857234
`https://mabe.int.prod.ci-aldi.com/mabe/api/v1/product/catalog?catalogCode=StructureGroup_1588161341857234&sort=recommended&currentPage=0&pageSize=100`

BIO Sortiment (201 products) - StructureGroup_1588161394387094
`https://mabe.int.prod.ci-aldi.com/mabe/api/v1/product/catalog?catalogCode=StructureGroup_1588161394387094&sort=recommended&currentPage=0&pageSize=100`

However, there also seem to be a plethora of subcategories and I'm not sure whether you'd even get all existing products via the category-based approach.
Therefore, it's maybe smarter to just use the search endpoint and search for generic terms (e.g., butter, milch, brot, ...). While you'd still miss many products you'd cover at least the products that are of major interest for the average consumer.

BTW penny.at seems to support easy retrieval via wildcard search again (however, the number of queryable products seems to be incomplete):
`https://www.penny.at/api/products/search/*?page=0&pageSize=500`
